/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "500": string;
        "1001": string;
        "1002": string;
        "1011": string;
        "1021": string;
        "1031": string;
    };
    "message": {
        "SUCCESS": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
